#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function

import argparse
import datetime

import boto3.session
import six
from dateutil.tz import tzutc

parser = argparse.ArgumentParser(
    description="Shows summary about 'Reserved' and 'On-demand' elasticache instances")
parser.add_argument("--aws-access-key", type=str, default=None,
                    help="AWS Access Key ID. Defaults to the value of the "
                         "AWS_ACCESS_KEY_ID environment variable (if set)")
parser.add_argument("--aws-secret-key", type=str, default=None,
                    help="AWS Secret Access Key. Defaults to the value of the "
                         "AWS_SECRET_ACCESS_KEY environment variable (if set)")
parser.add_argument("--region", type=str, default="cn-north-1",
                    help="AWS Region name. Default is 'cn-north-1'")
parser.add_argument("-w", "--warn-time", type=int, default=30,
                    help="Expire period for reserved instances in days. "
                         "Default is '30 days'")
args = parser.parse_args()

def instance_header():
    return ("\t(%s)\t%12s\t%s" %("Count", "Engine", "Instance"))

def expire_header():
    return ("\t(%s)\t%36s\t%14s\t%s" %("ID", "Type", "Engine", "Region"))

session = boto3.session.Session(region_name=args.region,
                                aws_access_key_id=args.aws_access_key,
                                aws_secret_access_key=args.aws_secret_key)

elasticache_client = session.client('elasticache')
clusters =  elasticache_client.describe_cache_clusters()['CacheClusters']

running_instances = {}
for c in clusters:
    if c['CacheClusterStatus'] != 'available':
        continue
    if not c['PreferredAvailabilityZone'].startswith(args.region):
        continue
    a_zone = args.region
    key = (c['Engine'], c['CacheNodeType'], a_zone)
    running_instances[key] = running_instances.get(key, 0) + 1

reserved_instances = {}
soon_expire_ri = {}

reserved_elasticache_instances = elasticache_client.describe_reserved_cache_nodes()
reservations = reserved_elasticache_instances['ReservedCacheNodes']
now = datetime.datetime.utcnow().replace(tzinfo=tzutc())
for ri in reservations:
    if ri['State'] == 'retired':
        continue
    ri_id = ri['ReservedCacheNodesOfferingId']
    ri_type = ri['CacheNodeType']
    ri_count = ri['CacheNodeCount']
    ri_engine = ri['ProductDescription']
    key = (ri_engine, ri_type, args.region)
    reserved_instances[key] = \
        reserved_instances.get(key, 0) + ri_count
    expire_time = ri['StartTime'] + datetime.timedelta(seconds=ri['Duration'])
    if (expire_time - now) < datetime.timedelta(days=args.warn_time):
        soon_expire_ri[ri_id] = (ri_type, ri_engine, args.region, expire_time)

diff = dict([(x, reserved_instances[x] - running_instances.get(x, 0))
             for x in reserved_instances])

for pkey in running_instances:
    if pkey not in reserved_instances:
        diff[pkey] = -running_instances[pkey]

unused_ri = {}
unreserved_instances = {}
for k, v in six.iteritems(diff):
    if v > 0:
        unused_ri[k] = v
    elif v < 0:
        unreserved_instances[k] = -v

# Report
print("Unused reserved Elasticache instances:")
print(instance_header())
for k, v in sorted(six.iteritems(unused_ri), key=lambda x: x[0]):
    print("\t(%s)\t%12s\t%s" %(v, k[0], k[1]))
if not unused_ri:
    print("\tNone")
print("")

print("Expiring soon (less than %sd) reserved Elasticache instances:" % args.warn_time)
print(expire_header())
for k, v in sorted(six.iteritems(soon_expire_ri), key=lambda x: x[1][:2]):
    print("\t%s\t%12s\t%s\t%s\t%s" %(k, v[0], v[1], v[2], v[3].strftime('%Y-%m-%d')))
if not soon_expire_ri:
    print("\tNone")
print("")

print("On-demand Elasticache instances, which haven't got a reserved Elasticache instance:")
print(instance_header())
for k, v in sorted(six.iteritems(unreserved_instances), key=lambda x: x[0]):
    print("\t(%s)\t%12s\t%s" %(v, k[0], k[1]))
if not unreserved_instances:
    print("\tNone")
print("")

print("Running on-demand Elasticache instances: %s" % sum(running_instances.values()))
print("Reserved Elasticache instances:          %s" % sum(reserved_instances.values()))
print("")
